######################## default configuration ####################
baseURL = "https://delightful-moss-0ff592e00.azurestaticapps.net/"
title = "Azure Static Web Apps TEST"
languageName = "jp"
theme = "m10c"
paginate = 5

[params]
  author = "Keruru"
  description = "ここはAzure Static Web Appsをお試ししているサイトです。"
  [[params.social]]
    name = "github"
    url = "https://github.com/1484/azure-hugo/"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/keruru"

